"""initial schema

Revision ID: 946582233830
Revises: 
Create Date: 2026-08-26 16:02:19.867508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946582233830'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_piles',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('pile_code', sa.String(length=20), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=10), nullable=True),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('charge_mode', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('power_kw', sa.Float(), nullable=True),
    sa.Column('price_charging', sa.Float(), nullable=True),
    sa.Column('price_idle', sa.Float(), nullable=True),
    # FK spot_id → parking_spots 拆到 parking_spots 建表后补（PG 建表时校验引用表存在）
    sa.UniqueConstraint('pile_code')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('device_code', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=True),
    sa.Column('last_maintenance_time', sa.DateTime(), nullable=True),
    sa.Column('power_w', sa.Float(), nullable=True),
    sa.Column('is_on', sa.Boolean(), nullable=True),
    sa.Column('stream_url', sa.String(length=500), nullable=True),
    sa.UniqueConstraint('device_code')
    )
    op.create_table('energy_records',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('power_usage', sa.Float(), nullable=True),
    sa.Column('record_time', sa.DateTime(), nullable=True),
    sa.Column('power_kw', sa.Float(), nullable=True),
    sa.Column('device_category', sa.String(length=30), nullable=True),
    )
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('lv', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    )
    op.create_table('event_refresh_marks',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('last_refresh', sa.DateTime(), nullable=True),
    )
    op.create_table('fire_alarm_stats',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_alarms', sa.Integer(), nullable=True),
    sa.Column('high_risk', sa.Integer(), nullable=True),
    sa.Column('smoke', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('co', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.Integer(), nullable=True),
    )
    op.create_table('floor_gates',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('gate_code', sa.String(length=20), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('last_action_time', sa.DateTime(), nullable=True),
    sa.UniqueConstraint('gate_code')
    )
    op.create_table('holiday_configs',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('holiday_type', sa.String(length=20), nullable=True),
    sa.Column('peak_factor', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    )
    op.create_table('parking_spots',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('spot_code', sa.String(length=20), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=10), nullable=True),
    sa.Column('x_coord', sa.Float(), nullable=True),
    sa.Column('y_coord', sa.Float(), nullable=True),
    sa.Column('spot_type', sa.String(length=20), nullable=True),
    sa.Column('spot_size', sa.String(length=10), nullable=True),
    sa.Column('is_charging_spot', sa.Boolean(), nullable=True),
    sa.Column('charging_pile_id', sa.Integer(), nullable=True),
    sa.Column('is_special', sa.Boolean(), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['charging_pile_id'], ['charging_piles.id'], ),
    sa.UniqueConstraint('spot_code')
    )
    # 补环形外键：charging_piles.spot_id → parking_spots.id
    # （PG 建表时校验被引用表必须存在，故拆到 parking_spots 建完后 ALTER 补；
    #   batch 模式：SQLite 走复制重建，PG 走普通 ALTER）
    with op.batch_alter_table('charging_piles') as batch_op:
        batch_op.create_foreign_key('fk_charging_piles_spot_id', 'parking_spots',
                                    ['spot_id'], ['id'])
    op.create_table('peak_hour_stats',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=True),
    sa.Column('exit_count', sa.Integer(), nullable=True),
    sa.Column('is_peak', sa.Boolean(), nullable=True),
    sa.Column('peak_type', sa.String(length=20), nullable=True),
    sa.Column('occupancy_rate', sa.Float(), nullable=True),
    sa.Column('weather', sa.String(length=20), nullable=True),
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('user_tag', sa.String(length=50), nullable=True),
    sa.Column('total_parking_count', sa.Integer(), nullable=True),
    sa.Column('monthly_parking_count', sa.Integer(), nullable=True),
    sa.Column('avg_duration', sa.Float(), nullable=True),
    sa.Column('preferred_floor', sa.Integer(), nullable=True),
    sa.Column('preferred_zone', sa.String(length=10), nullable=True),
    sa.Column('preferred_spot_type', sa.String(length=20), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('peak_entry_hour', sa.Integer(), nullable=True),
    sa.Column('peak_exit_hour', sa.Integer(), nullable=True),
    sa.Column('active_months', sa.Integer(), nullable=True),
    sa.Column('consecutive_peak_entry', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=True),
    sa.Column('vehicle_size', sa.String(length=10), nullable=True),
    sa.Column('is_electric', sa.Boolean(), nullable=True),
    sa.Column('owner_contact', sa.String(length=50), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('parking_duration', sa.Integer(), nullable=True),
    sa.Column('assigned_floor', sa.Integer(), nullable=True),
    sa.Column('assigned_zone', sa.String(length=10), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('user_tag', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('zone_code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('normal_light_on', sa.Boolean(), nullable=True),
    sa.Column('sound_light_on', sa.Boolean(), nullable=True),
    sa.Column('occupied_count', sa.Integer(), nullable=True),
    sa.Column('total_spots', sa.Integer(), nullable=True),
    )
    op.create_table('charging_records',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('pile_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('charge_mode', sa.String(length=10), nullable=True),
    sa.Column('start_battery', sa.Float(), nullable=True),
    sa.Column('end_battery', sa.Float(), nullable=True),
    sa.Column('total_kwh', sa.Float(), nullable=True),
    sa.Column('is_full', sa.Boolean(), nullable=True),
    sa.Column('total_fee', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['pile_id'], ['charging_piles.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    )
    op.create_table('device_maintenances',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_code', sa.String(length=50), nullable=True),
    sa.Column('maintenance_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    )
    op.create_table('parking_assignments',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('option1_spot_id', sa.Integer(), nullable=True),
    sa.Column('option2_spot_id', sa.Integer(), nullable=True),
    sa.Column('selected_spot_id', sa.Integer(), nullable=True),
    sa.Column('need_charging', sa.Boolean(), nullable=True),
    sa.Column('charge_mode', sa.String(length=10), nullable=True),
    sa.Column('assigned_floor', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['option1_spot_id'], ['parking_spots.id'], ),
    sa.ForeignKeyConstraint(['option2_spot_id'], ['parking_spots.id'], ),
    sa.ForeignKeyConstraint(['selected_spot_id'], ['parking_spots.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    )
    op.create_table('parking_records',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('spot_code', sa.String(length=20), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=10), nullable=True),
    sa.Column('total_fee', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['parking_spots.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先删补的环形外键（否则 PG 下 drop parking_spots 报依赖错误）
    with op.batch_alter_table('charging_piles') as batch_op:
        batch_op.drop_constraint('fk_charging_piles_spot_id', type_='foreignkey')
    op.drop_table('parking_records')
    op.drop_table('parking_assignments')
    op.drop_table('device_maintenances')
    op.drop_table('charging_records')
    op.drop_table('zones')
    op.drop_table('vehicles')
    op.drop_table('user_profiles')
    op.drop_table('peak_hour_stats')
    op.drop_table('parking_spots')
    op.drop_table('holiday_configs')
    op.drop_table('floor_gates')
    op.drop_table('fire_alarm_stats')
    op.drop_table('event_refresh_marks')
    op.drop_table('event_logs')
    op.drop_table('energy_records')
    op.drop_table('devices')
    op.drop_table('charging_piles')
    # ### end Alembic commands ###
